// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:reflactable_project/form_class.dart' as prefix1;
import 'package:reflactable_project/reflector.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'FormDeclaration',
            r'.FormDeclaration',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 9],
            const <int>[10, 11, 12, 13, 14, 3, 4, 5, 6, 7, 8],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.FormDeclaration() : null},
            0,
            0,
            const <int>[],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'name', 67239941, 0, const prefix0.Reflector(),
            -1, -1, -1, null, const <Object>[
          const prefix1.DynamicFieldAttribute(
              label: 'Name and Surname', order: 1)
        ]),
        r.VariableMirrorImpl(r'age', 67239941, 0, const prefix0.Reflector(), -1,
            -1, -1, null, const <Object>[
          const prefix1.DynamicFieldAttribute(label: 'Age', order: 1)
        ]),
        r.VariableMirrorImpl(r'isMarried', 67239941, 0,
            const prefix0.Reflector(), -1, -1, -1, null, const <Object>[
          const prefix1.DynamicFieldAttribute(
              label: 'Are you married?', order: 1)
        ]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 3),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 8),
        r.MethodMirrorImpl(r'', 64, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[3],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[4], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'_name', 67240038, 4, const prefix0.Reflector(),
            -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_age', 67240038, 6, const prefix0.Reflector(),
            -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_isMarried', 67240038, 8,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'other', 134348806, 10,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 134348806, 12,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null)
      ],
      <Type>[prefix1.FormDeclaration],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'name': (dynamic instance) => instance.name,
        r'age': (dynamic instance) => instance.age,
        r'isMarried': (dynamic instance) => instance.isMarried
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'age=': (dynamic instance, value) => instance.age = value,
        r'isMarried=': (dynamic instance, value) => instance.isMarried = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:reflactable_project/form_class.dart'),
            const prefix0.Reflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
